apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: employees 
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 81
      nodePort: 30000
  selector:
    app: employees